typography_spectrum: 0.9639499683398753
color:
  brandStrength: 0.09405402722768486
  lightness: 0.8049091154243797
  saturation: 0.3931191547308117
  rhythmicContrast: 0.03409324702806771
  brandColors:
    - '#6B685C'
    - '#484745'
    - '#ADB3BF'
    - '#B78C6F'
    - '#D7D7DA'
layout_spectrum: 0.7018408270087093
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e293c583-7b8d-487a-9528-1ac693805e1a.jpg
name: COMBO HOMES
navigation:
  - name: About
    url: www.combohomes.com.au/about
    type: external
title: Dual Occupancy
description: positive gearing
